-- MySQL Script generated by MySQL Workbench
-- qui 30 out 2025 22:44:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beeTechDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beeTechDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beeTechDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beeTechDB` ;

-- -----------------------------------------------------
-- Table `beeTechDB`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`agenteNegocios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`agenteNegocios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`apicultor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`apicultor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpfCnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpfCnpj_UNIQUE` (`cpfCnpj` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`apiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`apiario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(50) NOT NULL,
  `id_apicultor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apicultor_apiario_idx` (`id_apicultor` ASC) VISIBLE,
  CONSTRAINT `fk_apiario_apicultor`
    FOREIGN KEY (`id_apicultor`)
    REFERENCES `beeTechDB`.`apicultor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_apicultor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_apicultor_UNIQUE` (`id_apicultor` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_apicultor`
    FOREIGN KEY (`id_apicultor`)
    REFERENCES `beeTechDB`.`apicultor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`bem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`bem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATE NOT NULL,
  `id_inventario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bem_inventario_idx` (`id_inventario` ASC) VISIBLE,
  CONSTRAINT `fk_bem_inventario`
    FOREIGN KEY (`id_inventario`)
    REFERENCES `beeTechDB`.`inventario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(45) NOT NULL,
  `id_apiario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_caixa_apiario_idx` (`id_apiario` ASC) VISIBLE,
  CONSTRAINT `fk_caixa_apiario`
    FOREIGN KEY (`id_apiario`)
    REFERENCES `beeTechDB`.`apiario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`gasto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('TRANSPORTE', 'INSUMOS', 'MANUTENÇAO') NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  `id_apicultor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gasto_apicultor_idx` (`id_apicultor` ASC) VISIBLE,
  CONSTRAINT `fk_gasto_apicultor`
    FOREIGN KEY (`id_apicultor`)
    REFERENCES `beeTechDB`.`apicultor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beeTechDB`.`producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beeTechDB`.`producao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('MEL', 'CERA', 'PROPOLIS') NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `data` DATE NOT NULL,
  `id_caixa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producao_caixa_idx` (`id_caixa` ASC) VISIBLE,
  CONSTRAINT `fk_producao_caixa`
    FOREIGN KEY (`id_caixa`)
    REFERENCES `beeTechDB`.`caixa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

---------------------------INSERTS------------------------
USE beeTechDB;
INSERT INTO administrador (nome, cpf, telefone, senha_hash)
VALUES (
    'Maicon',
    '1234',
    '0000000',
    '$2a$10$YWsPfCGTyCVVmz185BaRUuN0iQGo6Qnea.csNbMMi8gs1L.Xo51F2'
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
